### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by liruipeng** [jwangjie/Gaussian-Processes-Regression-Tutorial#3]
https://raw.githubusercontent.com/jwangjie/Gaussian-Processes-Regression-Tutorial/master/tex/f4b3b11509dda9897b014202bf8a7df3.svg

Should be

$K_{*}^T K^{-1} f$

**Comment by jwangjie** [comment]
Thanks for pointing it out. I missed a `-1` on `K`, it should be $K_{*} ^T K^{-1} f$ shown at https://colab.research.google.com/github/jwangjie/Gaussian-Processes-Regression-Tutorial/blob/master/gpr_tutorial.ipynb#scrollTo=dmfc4mPu9v_U

**Comment by Darcy-vision** [comment]
I have come across the same error in the paper you have posted on arXiv. It would be greatly appreciated if you could make the correction on your [paper](https://arxiv.org/abs/2009.10862). 😄
